#!/bin/bash

# gather system data
uname -nr

# read arguments
inputfile=$1
desturl=$2

for f in ./*.h*; do
  rm -v $f
done


# load necessary modules
#source /cvmfs/oasis.opensciencegrid.org/osg/modules/lmod/current/init/bash
#module load python/3.5.2 all-pkgs gcc/6.2.0 boost hdf5 || exit 1

# unpack package
export pkgname='hic-hvq'
tar xzf $pkgname.tar.gz

# set environment variables
prefix="$(pwd)/$pkgname"
export PATH="$prefix/bin:$PATH"
export XDG_DATA_HOME="$prefix/share"
export PYTHONPATH="$(echo $prefix/lib64/python*/site-packages)":"$(echo $prefix/lib/python*/site-packages)"
echo $XDG_DATA_HOME
# go!
# first, run medium
run-medium-events $inputfile || exit 1
# second, run hvq event 
run-hvq-events JetData.h5 initial.hdf || exit 1
# transfer results
# try to be fault-tolerant
#globus() {
#  globus-url-copy \
#    -verbose -create-dest -restart -stall-timeout 30 $@ \
#    results $desturl
#}

#for i in {1..5}; do
#  globus && break
#  sleep 5 && false
#done || \
#  globus -no-data-channel-authentication -no-third-party-transfers
